### PR TITLE
New Localization: Turkish

### PR DESCRIPTION
**Pull request by imesut**
Hello,

Firstly congratulations on the idea.

I wanted to contribute to Turkish localization on this project.

If possible, I want to test and refine Turkish localization with a Testflght release.

### CODE REVIEW

**Comment by SimoneMontalto** [comment]
Thank you for your help 😊 Send me your Apple ID email so that I can add you to TestFlight beta. 


PS. Today I’ve added new strings. Could you check them?

**Comment by imesut** [comment]
Hi Simone,

You're welcome. My apple id is: mresyilmaz@gmail.com

As I noticed, you did add 15 new strings and removed two strings.

I've added these changes in my commit id below:
43417554dca1973387c95a6c89b072e190368fea

**Comment by SimoneMontalto** [comment]
Added to the TestFlight Beta list.

**Review by SimoneMontalto — APPROVED** [review]

**Comment by SimoneMontalto** [comment]
Can I merge this PR?

**Comment by imesut** [comment]
I just saw something to be corrected; I'll share it within two days.

**Comment by imesut** [comment]
Hi Simone,
Tested the app with Turkish translation in deep. Hopefully, I just found a few problems and fixed these.

**Comment by SimoneMontalto** [comment]
Thanks, I'm going to release a new build on TestFlight.

**Review by SimoneMontalto — APPROVED** [review]

**Comment by imesut** [comment]
I checked the new release, it's okay.

**Pull request merged**
